import type { SupportedSourceLanguage } from '@/infrastructure/analysis/project-analysis-file-descriptions';

export type PhpPathConstantName = keyof typeof PHP_PATH_CONSTANT_BASE_PATHS;

export const SUPPORTED_SOURCE_EXTENSIONS = new Map<string, SupportedSourceLanguage>([
  ['.ts', 'typescript'],
  ['.tsx', 'typescript'],
  ['.mts', 'typescript'],
  ['.cts', 'typescript'],
  ['.js', 'javascript'],
  ['.jsx', 'javascript'],
  ['.mjs', 'javascript'],
  ['.cjs', 'javascript'],
  ['.vue', 'vue'],
  ['.kt', 'kotlin'],
  ['.kts', 'kotlin'],
  ['.php', 'php'],
  ['.java', 'java'],
]);

export const SOURCE_RESOLUTION_EXTENSIONS = [
  '.ts',
  '.tsx',
  '.mts',
  '.cts',
  '.js',
  '.jsx',
  '.mjs',
  '.cjs',
  '.vue',
  '.kt',
  '.kts',
  '.php',
  '.java',
  '.json',
] as const;

export const JAVASCRIPT_RUNTIME_EXTENSIONS = new Set(['.js', '.jsx', '.mjs', '.cjs']);
export const MONOREPO_ROOT_DIRECTORIES = new Set(['apps', 'libs', 'modules', 'packages']);
export const ROOT_AREA_NAMES = new Set([
  'api',
  'application',
  'core',
  'domain',
  'infrastructure',
  'main',
  'preload',
  'renderer',
  'shared',
  'test',
  'tests',
  'util',
  'utils',
]);
export const LOW_GRANULARITY_AREAS = new Set([
  'application',
  'core',
  'infrastructure',
  'main',
  'preload',
  'renderer',
  'shared',
  'util',
]);
export const TEST_PATH_SEGMENTS = new Set(['test', 'tests', '__test__', '__tests__', '__mocks__']);
export const STRUCTURAL_PATH_SEGMENTS = new Set([
  'command',
  'commands',
  'controller',
  'controllers',
  'decorator',
  'decorators',
  'domain',
  'domains',
  'dto',
  'dtos',
  'entity',
  'entities',
  'exception',
  'exceptions',
  'factory',
  'factories',
  'filter',
  'filters',
  'guard',
  'guards',
  'handler',
  'handlers',
  'interceptor',
  'interceptors',
  'mapper',
  'mappers',
  'middleware',
  'middlewares',
  'model',
  'models',
  'module',
  'modules',
  'pipe',
  'pipes',
  'policy',
  'policies',
  'query',
  'queries',
  'repository',
  'repositories',
  'service',
  'services',
  'strategy',
  'strategies',
  'type',
  'types',
  'util',
  'utils',
  'validator',
  'validators',
]);
export const DEFAULT_FEATURE_SCOPE_LIMIT = 2;
export const DEFAULT_DIRECTORY_SUMMARY_LIMIT = 12;
export const DEFAULT_CONNECTION_LIMIT = 12;
export const PHP_APPLICATION_UNBOUNDED_SCOPE_ROOTS = new Set([
  'controller',
  'controllers',
  'domain',
  'model',
  'models',
  'service',
  'services',
]);
export const PHP_PATH_CONSTANT_BASE_PATHS = {
  APPPATH: 'application',
  BASEPATH: 'system',
  FCPATH: '.',
} as const;
export const PHPDOC_TYPE_TAGS = new Set([
  'param',
  'return',
  'var',
  'throws',
  'property',
  'property-read',
  'property-write',
  'mixin',
  'extends',
  'implements',
  'use',
  'phpstan-param',
  'phpstan-return',
  'phpstan-var',
  'phpstan-throws',
  'phpstan-property',
  'phpstan-property-read',
  'phpstan-property-write',
  'phpstan-mixin',
  'phpstan-extends',
  'phpstan-implements',
  'phpstan-use',
  'psalm-param',
  'psalm-return',
  'psalm-var',
  'psalm-throws',
  'psalm-property',
  'psalm-property-read',
  'psalm-property-write',
  'psalm-mixin',
  'psalm-extends',
  'psalm-implements',
  'psalm-use',
]);
export const PHPDOC_RESERVED_TYPE_NAMES = new Set([
  '$this',
  'array',
  'array-key',
  'bool',
  'boolean',
  'callable',
  'callable-array',
  'callable-string',
  'class-string',
  'closed-resource',
  'double',
  'false',
  'float',
  'from',
  'int',
  'integer',
  'interface-string',
  'iterable',
  'key-of',
  'list',
  'literal-string',
  'lowercase-string',
  'mixed',
  'negative-int',
  'never',
  'non-empty-array',
  'non-empty-list',
  'non-empty-string',
  'non-negative-int',
  'non-positive-int',
  'null',
  'numeric',
  'numeric-string',
  'object',
  'open-resource',
  'parent',
  'positive-int',
  'resource',
  'scalar',
  'self',
  'static',
  'string',
  'this',
  'to',
  'trait-string',
  'true',
  'value-of',
  'void',
]);
